# coding: utf-8

# flake8: noqa
"""
    Eliona REST API

    The Eliona REST API provides unified access to the resources and data within an Eliona environment.<br> <br> This documentation corresponds to Eliona release 14.2. For previous Eliona releases, please refer to the matching REST API version below:<br> <br> Eliona v14.2: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> Eliona v14.1: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> Eliona v14.0: [2.8.7](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.8.7/openapi.yaml)<br> Eliona v13.2: [2.7.0](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.7.0/openapi.yaml)<br> Eliona v13.1: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> Eliona v13.0: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> Eliona v12.1: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> Eliona v12.0: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> [Preview Beta](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/heads/develop/openapi.yaml)<br> 

    The version of the OpenAPI document: 2.9.6
    Contact: hello@eliona.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from eliona.api_client2.models.agent import Agent
    from eliona.api_client2.models.agent_class import AgentClass
    from eliona.api_client2.models.agent_device_general import AgentDeviceGeneral
    from eliona.api_client2.models.agent_device_mapping_general import AgentDeviceMappingGeneral
    from eliona.api_client2.models.aggregation import Aggregation
    from eliona.api_client2.models.alarm import Alarm
    from eliona.api_client2.models.alarm_listen import AlarmListen
    from eliona.api_client2.models.alarm_priority import AlarmPriority
    from eliona.api_client2.models.alarm_rule import AlarmRule
    from eliona.api_client2.models.app import App
    from eliona.api_client2.models.asset import Asset
    from eliona.api_client2.models.asset_dry_run import AssetDryRun
    from eliona.api_client2.models.asset_identify_by import AssetIdentifyBy
    from eliona.api_client2.models.asset_listen import AssetListen
    from eliona.api_client2.models.asset_type import AssetType
    from eliona.api_client2.models.asset_type_attribute import AssetTypeAttribute
    from eliona.api_client2.models.asset_type_category import AssetTypeCategory
    from eliona.api_client2.models.asset_type_category_property import AssetTypeCategoryProperty
    from eliona.api_client2.models.attachment import Attachment
    from eliona.api_client2.models.attribute_display import AttributeDisplay
    from eliona.api_client2.models.calculation_rule import CalculationRule
    from eliona.api_client2.models.dashboard import Dashboard
    from eliona.api_client2.models.data import Data
    from eliona.api_client2.models.data_aggregated import DataAggregated
    from eliona.api_client2.models.data_listen import DataListen
    from eliona.api_client2.models.data_subtype import DataSubtype
    from eliona.api_client2.models.data_trend_aggregated import DataTrendAggregated
    from eliona.api_client2.models.dry_run_general import DryRunGeneral
    from eliona.api_client2.models.iosys_agent_device import IosysAgentDevice
    from eliona.api_client2.models.iosys_agent_device_mapping import IosysAgentDeviceMapping
    from eliona.api_client2.models.message import Message
    from eliona.api_client2.models.message_receipt import MessageReceipt
    from eliona.api_client2.models.node import Node
    from eliona.api_client2.models.notification import Notification
    from eliona.api_client2.models.patch import Patch
    from eliona.api_client2.models.project import Project
    from eliona.api_client2.models.project_role import ProjectRole
    from eliona.api_client2.models.project_user import ProjectUser
    from eliona.api_client2.models.tag import Tag
    from eliona.api_client2.models.translation import Translation
    from eliona.api_client2.models.user import User
    from eliona.api_client2.models.widget import Widget
    from eliona.api_client2.models.widget_data import WidgetData
    from eliona.api_client2.models.widget_type import WidgetType
    from eliona.api_client2.models.widget_type_element import WidgetTypeElement
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from eliona.api_client2.models.agent import Agent
from eliona.api_client2.models.agent_class import AgentClass
from eliona.api_client2.models.agent_device_general import AgentDeviceGeneral
from eliona.api_client2.models.agent_device_mapping_general import AgentDeviceMappingGeneral
from eliona.api_client2.models.aggregation import Aggregation
from eliona.api_client2.models.alarm import Alarm
from eliona.api_client2.models.alarm_listen import AlarmListen
from eliona.api_client2.models.alarm_priority import AlarmPriority
from eliona.api_client2.models.alarm_rule import AlarmRule
from eliona.api_client2.models.app import App
from eliona.api_client2.models.asset import Asset
from eliona.api_client2.models.asset_dry_run import AssetDryRun
from eliona.api_client2.models.asset_identify_by import AssetIdentifyBy
from eliona.api_client2.models.asset_listen import AssetListen
from eliona.api_client2.models.asset_type import AssetType
from eliona.api_client2.models.asset_type_attribute import AssetTypeAttribute
from eliona.api_client2.models.asset_type_category import AssetTypeCategory
from eliona.api_client2.models.asset_type_category_property import AssetTypeCategoryProperty
from eliona.api_client2.models.attachment import Attachment
from eliona.api_client2.models.attribute_display import AttributeDisplay
from eliona.api_client2.models.calculation_rule import CalculationRule
from eliona.api_client2.models.dashboard import Dashboard
from eliona.api_client2.models.data import Data
from eliona.api_client2.models.data_aggregated import DataAggregated
from eliona.api_client2.models.data_listen import DataListen
from eliona.api_client2.models.data_subtype import DataSubtype
from eliona.api_client2.models.data_trend_aggregated import DataTrendAggregated
from eliona.api_client2.models.dry_run_general import DryRunGeneral
from eliona.api_client2.models.iosys_agent_device import IosysAgentDevice
from eliona.api_client2.models.iosys_agent_device_mapping import IosysAgentDeviceMapping
from eliona.api_client2.models.message import Message
from eliona.api_client2.models.message_receipt import MessageReceipt
from eliona.api_client2.models.node import Node
from eliona.api_client2.models.notification import Notification
from eliona.api_client2.models.patch import Patch
from eliona.api_client2.models.project import Project
from eliona.api_client2.models.project_role import ProjectRole
from eliona.api_client2.models.project_user import ProjectUser
from eliona.api_client2.models.tag import Tag
from eliona.api_client2.models.translation import Translation
from eliona.api_client2.models.user import User
from eliona.api_client2.models.widget import Widget
from eliona.api_client2.models.widget_data import WidgetData
from eliona.api_client2.models.widget_type import WidgetType
from eliona.api_client2.models.widget_type_element import WidgetTypeElement

""",
            name=__name__,
            doc=__doc__,
        )
    )
