# coding: utf-8

"""
    Eliona REST API

    The Eliona REST API enables unified access to the resources and data of an Eliona environment.

    The version of the OpenAPI document: 2.9.1
    Contact: hello@eliona.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AgentClass(str, Enum):
    """
    The class of an agent
    """

    """
    allowed enum values
    """
    AGENT_CLASS_IOSYS = 'iosys'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AgentClass from a JSON string"""
        return cls(json.loads(json_str))


