# coding: utf-8

"""
    Eliona REST API

    The Eliona REST API provides unified access to the resources and data within an Eliona environment.<br> <br> This documentation corresponds to Eliona release 14.2. For previous Eliona releases, please refer to the matching REST API version below:<br> <br> Eliona v14.2: [2.10.5](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.10.5/openapi.yaml)<br> Eliona v14.1: [2.9.4](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.9.4/openapi.yaml)<br> Eliona v14.0: [2.8.7](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.8.7/openapi.yaml)<br> Eliona v13.2: [2.7.0](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.7.0/openapi.yaml)<br> Eliona v13.1: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> Eliona v13.0: [2.6.12](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.12/openapi.yaml)<br> Eliona v12.1: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> Eliona v12.0: [2.6.1](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/tags/v2.6.1/openapi.yaml)<br> [Preview Beta](https://api.eliona.io/?https://raw.githubusercontent.com/eliona-smart-building-assistant/eliona-api/refs/heads/develop/openapi.yaml)<br> 

    The version of the OpenAPI document: 2.9.6
    Contact: hello@eliona.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Ticket(BaseModel):
    """
    A ticket and task record
    """ # noqa: E501
    ticket_id: Optional[StrictInt] = Field(default=None, description="The id of the ticket", alias="ticketId")
    parent_id: Optional[StrictInt] = Field(default=None, description="The id of the parent ticket", alias="parentId")
    title: Optional[StrictStr] = Field(default=None, description="Title of the ticket")
    description: Optional[StrictStr] = Field(default=None, description="Description of the ticket")
    priority: Optional[StrictInt] = Field(default=None, description="Priority of the ticket")
    reason: Optional[StrictStr] = Field(default=None, description="Reason or type of the ticket")
    state: Optional[StrictStr] = Field(default=None, description="Current state of the ticket")
    contact: Optional[Dict[str, Any]] = Field(default=None, description="Contact information as JSON object")
    tags: Optional[List[StrictStr]] = Field(default=None, description="List of associated tags")
    created_by: Optional[StrictStr] = Field(default=None, description="User who created the ticket", alias="createdBy")
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the ticket was created", alias="createdAt")
    assigned_to: Optional[StrictStr] = Field(default=None, description="User the ticket is assigned to", alias="assignedTo")
    assigned_at: Optional[datetime] = Field(default=None, description="Timestamp when the ticket was assigned", alias="assignedAt")
    closed_at: Optional[datetime] = Field(default=None, description="Timestamp when the ticket was closed", alias="closedAt")
    project_id: Optional[StrictStr] = Field(default=None, description="ID of the project to which the ticket belongs", alias="projectId")
    asset_id: Optional[StrictInt] = Field(default=None, description="ID of the associated asset", alias="assetId")
    alarm_id: Optional[StrictInt] = Field(default=None, description="ID of the associated alarm", alias="alarmId")
    alarm: Optional[Dict[str, Any]] = Field(default=None, description="Alarm data snapshot as JSON object")
    start_at: Optional[datetime] = Field(default=None, description="Scheduled start time", alias="startAt")
    end_at: Optional[datetime] = Field(default=None, description="Scheduled end time", alias="endAt")
    time_spent: Optional[StrictStr] = Field(default=None, description="Time spent on the ticket", alias="timeSpent")
    reference: Optional[StrictStr] = Field(default=None, description="External reference")
    modified_by: Optional[StrictStr] = Field(default=None, description="User who last modified the ticket", alias="modifiedBy")
    modified_at: Optional[datetime] = Field(default=None, description="Timestamp of last modification", alias="modifiedAt")
    __properties: ClassVar[List[str]] = ["ticketId", "parentId", "title", "description", "priority", "reason", "state", "contact", "tags", "createdBy", "createdAt", "assignedTo", "assignedAt", "closedAt", "projectId", "assetId", "alarmId", "alarm", "startAt", "endAt", "timeSpent", "reference", "modifiedBy", "modifiedAt"]

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['maintenance', 'error', 'service', 'cleaning', 'other']):
            raise ValueError("must be one of enum values ('maintenance', 'error', 'service', 'cleaning', 'other')")
        return value

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['staged', 'assigned', 'in-progress', 'completed', 'closed', 'canceled', 'delayed']):
            raise ValueError("must be one of enum values ('staged', 'assigned', 'in-progress', 'completed', 'closed', 'canceled', 'delayed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Ticket from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "ticket_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ticket_id (nullable) is None
        # and model_fields_set contains the field
        if self.ticket_id is None and "ticket_id" in self.model_fields_set:
            _dict['ticketId'] = None

        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict['parentId'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if contact (nullable) is None
        # and model_fields_set contains the field
        if self.contact is None and "contact" in self.model_fields_set:
            _dict['contact'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['createdBy'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['createdAt'] = None

        # set to None if assigned_to (nullable) is None
        # and model_fields_set contains the field
        if self.assigned_to is None and "assigned_to" in self.model_fields_set:
            _dict['assignedTo'] = None

        # set to None if assigned_at (nullable) is None
        # and model_fields_set contains the field
        if self.assigned_at is None and "assigned_at" in self.model_fields_set:
            _dict['assignedAt'] = None

        # set to None if closed_at (nullable) is None
        # and model_fields_set contains the field
        if self.closed_at is None and "closed_at" in self.model_fields_set:
            _dict['closedAt'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['projectId'] = None

        # set to None if asset_id (nullable) is None
        # and model_fields_set contains the field
        if self.asset_id is None and "asset_id" in self.model_fields_set:
            _dict['assetId'] = None

        # set to None if alarm_id (nullable) is None
        # and model_fields_set contains the field
        if self.alarm_id is None and "alarm_id" in self.model_fields_set:
            _dict['alarmId'] = None

        # set to None if alarm (nullable) is None
        # and model_fields_set contains the field
        if self.alarm is None and "alarm" in self.model_fields_set:
            _dict['alarm'] = None

        # set to None if start_at (nullable) is None
        # and model_fields_set contains the field
        if self.start_at is None and "start_at" in self.model_fields_set:
            _dict['startAt'] = None

        # set to None if end_at (nullable) is None
        # and model_fields_set contains the field
        if self.end_at is None and "end_at" in self.model_fields_set:
            _dict['endAt'] = None

        # set to None if time_spent (nullable) is None
        # and model_fields_set contains the field
        if self.time_spent is None and "time_spent" in self.model_fields_set:
            _dict['timeSpent'] = None

        # set to None if reference (nullable) is None
        # and model_fields_set contains the field
        if self.reference is None and "reference" in self.model_fields_set:
            _dict['reference'] = None

        # set to None if modified_by (nullable) is None
        # and model_fields_set contains the field
        if self.modified_by is None and "modified_by" in self.model_fields_set:
            _dict['modifiedBy'] = None

        # set to None if modified_at (nullable) is None
        # and model_fields_set contains the field
        if self.modified_at is None and "modified_at" in self.model_fields_set:
            _dict['modifiedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Ticket from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ticketId": obj.get("ticketId"),
            "parentId": obj.get("parentId"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "priority": obj.get("priority"),
            "reason": obj.get("reason"),
            "state": obj.get("state"),
            "contact": obj.get("contact"),
            "tags": obj.get("tags"),
            "createdBy": obj.get("createdBy"),
            "createdAt": obj.get("createdAt"),
            "assignedTo": obj.get("assignedTo"),
            "assignedAt": obj.get("assignedAt"),
            "closedAt": obj.get("closedAt"),
            "projectId": obj.get("projectId"),
            "assetId": obj.get("assetId"),
            "alarmId": obj.get("alarmId"),
            "alarm": obj.get("alarm"),
            "startAt": obj.get("startAt"),
            "endAt": obj.get("endAt"),
            "timeSpent": obj.get("timeSpent"),
            "reference": obj.get("reference"),
            "modifiedBy": obj.get("modifiedBy"),
            "modifiedAt": obj.get("modifiedAt")
        })
        return _obj


